### ISSUE TITLE
Regular Expression

### ISSUE THREAD

**Issue by AshleyAlexJacob** [AhmedRaja1/Form-Validator#1]
Hello Raja! Mate you can make this validator more efficient by adding RegExp for Email Validation. You checkout StackOverflow to add it.

**Comment by AhmedRaja1** [comment]
Yeah, I am putting all the validations in later projects, maybe a second version!
Thanks for always carefully going through my work!

**Comment by AhmedRaja1** [comment]
Also, the main reason behind letting it go was "As the front end uses Bootstrap" and bootstrap has got built-in simple validations like @ or email domain extensions.
